driver:
  name: vagrant

driver_config:
  require_chef_omnibus: latest

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-10.04
    run_list:
      - recipe[apt]
  - name: centos-6.6
    run_list:
      - recipe[yum-epel]
  - name: centos-7.1
    run_list:
      - recipe[yum-epel]

suites:
  - name: tomcat6
    excludes: ['centos-7.1']
    attributes: {}

  - name: tomcat7
    excludes: ['ubuntu-10.04']
    attributes: {tomcat: {base_version: 7}}